using System.Linq;
using LCARS.Database.Logs;

namespace LCARS
{
    public static class SeedData
    {
        public static void ReinitializeComputerCore(CoreContext context)
        {
            if (!context.PersonnelLogs.Any())
            {
                context.PersonnelLogs.AddRange(
                    Personal.CaptainsLog(@"Captain's Personal Log: I trust my concern over the problems of ship's Counselor Troi are not based merely on losing a highly valuable crew member. But it seems to me that she is trapped by a custom of her homeworld which the facts of 24th century life have made unwise and unworkable. I wish I could intervene."),
                    Personal.CaptainsLog(@"Captain's Personal Log: I'm entering the ship's holodeck where images of reality can be created by our ship's computer. Highly useful in crew training. Highly enjoyable when used for games and recreation."),
                    Personal.CaptainsLog(@"Captain's Personal Log: I am delighted with how the holodeck has created the fictional world of Dixon Hill, the 20th century detective who's been a hero of mine since childhood. The characters are meta-generated by the computer, of course yet they feel real… they seem real in every way.")
                    );
                context.SaveChanges();
            }
        }
    }
}
